version: '2'
services:
  manager:
    image: docker:stable-dind
    container_name: swarm-manager
    hostname: manager
    privileged: true
    ports:
      - "2375:2375"
      - "2377:2377"
      - "80:80"
    networks:
      static-network:
        ipv4_address: 172.20.128.5
  node1:
    image: docker:stable-dind
    container_name: swarm-node1
    hostname: node1
    privileged: true
    networks:
      static-network:
        ipv4_address: 172.20.128.3
  node2:
    image: docker:stable-dind
    container_name: swarm-node2
    hostname: node2
    privileged: true
    networks:
      static-network:
        ipv4_address: 172.20.128.4
networks:
  static-network:
    ipam:
      config:
        - subnet: 172.20.0.0/16
          #docker-compose v3+ do not use ip_range
          ip_range: 172.28.5.0/24
